### ISSUE TITLE
Tests fail when no Drone contexts exist

### ISSUE THREAD

**Issue by mikesir87** [arquillian/arquillian-recorder#10]
Quick question, as I'm not sure if this is a bug or if I'm actually doing something wrong.  I'm using the Graphene Screenshooter, by enabling it in my arquillian.xml.  It works flawlessly when running tests that use Drone.  

However, for tests that don't use Graphene, I get the exception below.  Example tests are container-mode tests where we're testing various beans or REST endpoints where we're using a Jersey client to test our endpoints.

Is there a suggested way to work around this issue?  Should we simply use a separate arquillian.xml for non-Drone tests?  Is there a way to programatically enable the screenshooter extension?  Is there something that can be done to prevent it from running if there is no Drone context?

```
java.lang.IllegalStateException: There is no context available for qualifier org.jboss.arquillian.drone.api.annotation.Default. Available contexts are [].
	at org.jboss.arquillian.graphene.context.GrapheneContextImpl$LazyContext.getContext(GrapheneContextImpl.java:302)
	at org.jboss.arquillian.graphene.context.GrapheneContextImpl$LazyContext$1.getTarget(GrapheneContextImpl.java:311)
	at org.jboss.arquillian.graphene.proxy.GrapheneProxyHandler.getTarget(GrapheneProxyHandler.java:149)
	at org.jboss.arquillian.graphene.proxy.GrapheneContextualHandler.invoke(GrapheneContextualHandler.java:114)
	at com.sun.proxy.$Proxy52.unwrap(Unknown Source)
	at org.arquillian.extension.recorder.screenshooter.browser.impl.BrowserScreenshooter.getTakingScreenshotsBrowser(BrowserScreenshooter.java:140)
	at org.arquillian.extension.recorder.screenshooter.browser.impl.BrowserScreenshooter.takeScreenshot(BrowserScreenshooter.java:110)
	at org.arquillian.extension.recorder.screenshooter.browser.impl.TakeScreenshotAndReportService.takeScreenshotAndReport(TakeScreenshotAndReportService.java:58)
	at org.arquillian.extension.recorder.screenshooter.browser.impl.ScreenshotTaker.onTakeScreenshot(ScreenshotTaker.java:79)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
	at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:99)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:81)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:145)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:116)
	at org.jboss.arquillian.core.impl.EventImpl.fire(EventImpl.java:67)
	at org.arquillian.extension.recorder.screenshooter.impl.ScreenshooterLifecycleObserver.afterTest(ScreenshooterLifecycleObserver.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
	at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:99)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:81)
	at org.jboss.arquillian.container.test.impl.client.ContainerEventController.createContext(ContainerEventController.java:142)
	at org.jboss.arquillian.container.test.impl.client.ContainerEventController.createAfterContext(ContainerEventController.java:134)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:88)
	at org.jboss.arquillian.testenricher.cdi.CreationalContextDestroyer.destory(CreationalContextDestroyer.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:88)
	at org.jboss.arquillian.junit.extension.UpdateTestResultBeforeAfter.update(UpdateTestResultBeforeAfter.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:88)
	at org.jboss.arquillian.test.impl.TestContextHandler.createTestContext(TestContextHandler.java:102)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:88)
	at org.jboss.arquillian.test.impl.TestContextHandler.createClassContext(TestContextHandler.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:88)
	at org.jboss.arquillian.test.impl.TestContextHandler.createSuiteContext(TestContextHandler.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:88)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:145)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:116)
	at org.jboss.arquillian.test.impl.EventTestRunnerAdaptor.after(EventTestRunnerAdaptor.java:103)
	at org.jboss.arquillian.junit.Arquillian$5.evaluate(Arquillian.java:277)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.jboss.arquillian.junit.Arquillian$2.evaluate(Arquillian.java:193)
	at org.jboss.arquillian.junit.Arquillian.multiExecute(Arquillian.java:345)
	at org.jboss.arquillian.junit.Arquillian.access$200(Arquillian.java:49)
	at org.jboss.arquillian.junit.Arquillian$3.evaluate(Arquillian.java:207)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.jboss.arquillian.junit.Arquillian.run(Arquillian.java:155)
	...
```

**Comment by davidmjames** [comment]
The multiple profiles or projects feel like a hack to me- I'm a fan of Aslak's strategy of making the screenshooter just not execute if no Drone/Graphene context is available.

I'm the primary maintainer of a test suite that includes a lot of Graphene tests, and a sizeable collection of REST-only tests. It seems almost trivial to add a quick check that a context is available before taking screenshots, vs the complexity of having to keep track of what tests use what and split them out. We have tests that migrate from one set to the other as new functionality is added, so the maintenance headache is notable.

**Comment by mikesir87** [comment]
Agreed.  Even if it's a config option to disable if no context exists, it would work for me.

**Comment by smiklosovic** [comment]
@davidmjames @mikesir87 

ok, I will try to resolve it this week.

**Comment by smiklosovic** [comment]
@mikesir87 @davidmjames could you please clone my Graphene fork where I pushed that fix (the branch drone_2.0.0.Alpha3_alignement) and try that?

Try it on this https://github.com/smiklosovic/web-test

In my case, when I have these dependencies on CP and I do not inject any webdriver into the test, and there is not webdriver configuration in arquillian.xml, these tests passes.

**Comment by lfryc** [comment]
The JIRA opened here: https://issues.jboss.org/browse/ARQGRA-467

**Comment by smiklosovic** [comment]
considered done

**Comment by michbeck100** [comment]
For me it's not fixed. I've added a comment to https://issues.jboss.org/browse/ARQGRA-467

**Comment by smiklosovic** [comment]
@MatousJobanek could you have a look and help Michael, please?

**Comment by MatousJobanek** [comment]
Hi, yeah sure

**Comment by MatousJobanek** [comment]
Hi, sorry for my looong inactivity - I was stuck with other work.
Here is the fix: https://github.com/arquillian/arquillian-graphene/pull/158/files
The commit contains also a simple test case.

**Comment by MatousJobanek** [comment]
@michbeck100 please, take a look and give it a try if you can. Thanks

**Comment by michbeck100** [comment]
I'll try, though i can't remember how to reproduce ;-).

**Comment by FibreFoX** [comment]
Maybe I have found a scenario when this happens: when there is no "default"-drone, this still fails to work for me.

src/test/resources/arquillian.xml
```xml
<?xml version="1.0" encoding="UTF-8"?>
<arquillian xmlns="http://jboss.org/schema/arquillian" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://jboss.org/schema/arquillian http://jboss.org/schema/arquillian/arquillian_1_0.xsd">
    <extension qualifier="webdriver-firefox">
        <property name="remote">true</property>
        <property name="remoteAddress">http://localhost:5555/wd/hub</property>
        <property name="browser">firefox</property>
    </extension>
    <extension qualifier="webdriver-chrome">
        <property name="remote">true</property>
        <property name="remoteAddress">http://localhost:5556/wd/hub</property>
        <property name="browser">chrome</property>
    </extension>
</arquillian>
```
src/test/java/SimpleWebsiteTest.java
```java
@RunWith(Arquillian.class)
@RunAsClient
public class SimpleWebsiteTest {

    @Drone
    @Chrome
    private WebDriver chrome;

    @Drone
    @Firefox
    private WebDriver firefox;

    @Test
    public void firstSimpleTest() {
        // any website should work
        browser.get("http://www.arquillian.org");
        Graphene.waitGui();
        Assert.fail();
    }
}
```

The browser-qualifiers are done like this:
```java
import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;
import org.jboss.arquillian.drone.api.annotation.Qualifier;

@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.FIELD, ElementType.PARAMETER})
@Qualifier
public @interface Chrome {

}
```

While Graphene supports multiple browsers running in parallel, there seems no documentation for the screenshooter to be controlled ... or am I missing something?
